### PR TITLE
Metaclass Factory

### LINKED ISSUE #2: Metaclass Factory
So required variables isn't hard-coded.

### PR DESCRIPTION
**Pull request by scolby33**
Closes #2

### CODE REVIEW

**Comment by scolby33** [comment]
@cthoyt how much do you hate this?

**Comment by cthoyt** [comment]
It's diabolical. I love it.

Though, it's a bit overkill. There's no reason to make this overcomplicated since this code won't be reused, right?

**Comment by scolby33** [comment]
It's less for reuse than it is for maybe putting `['FILES', 'NAME']` at the top of the file as a constant.

**Comment by cthoyt** [comment]
> It's less for reuse than it is for maybe putting `['FILES', 'NAME']` at the top of the file as a constant.

It already is a constant though... it's a class variable for a non-dynamic class

**Comment by scolby33** [comment]
Turns out this was a bad idea and mypy hates it, so skipping this for now.

**Pull request closed without merging**
