### PR TITLE
Update type annotation in EasyConfig._load_file

### LINKED ISSUE #6: Wrong type annotations
`EasyConfig._load_file` takes either a `Path` or a `TextIO`. It seems to work with a string, but this needs to be updated

https://github.com/scolby33/easy_config/blob/f7801583ba7a393188b2d90a66046892b9cb2345/tests/test_easy_config.py#L34

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #6 
Added str as allowed type.
Combine instance checking for str and Path since isinstance allows for a tuple to be given.

### CODE REVIEW

**Comment by scolby33** [comment]
Oops sorry I did this myself.

**Comment by cthoyt** [comment]
no PR cred? WTF is with these maintainers, amirite?

**Comment by scolby33** [comment]
I'll take it up with my supervisor.

**Comment by scolby33** [comment]
@cthoyt someone is mad about PR cred.

**Pull request closed without merging**
